### ISSUE TITLE
Add a GitHub logo directing users to this repository

### ISSUE THREAD

**Issue by rsrinath14** [pbdsce/advaith-website#21] opened 2021-07-04 14:39 UTC
There will be users who might considering contributing if a link to this repository is provided.

**Comment by ayushk1804** [comment] 2021-07-06 14:17
Hi @srinath1412001 would you like to work on this issue?

**Comment by rsrinath14** [comment] 2021-07-06 20:04
I would love to try, but i'm not familiar with the techstack..

**Comment by pururaj987** [comment] 2021-10-12 05:13
Hi @ayushk1804 , where would you like this GitHub logo to be placed ? Will it work if the logo is placed along with other platforms of Point Blank under the Event Hosts section ?

**Comment by ayushk1804** [comment] 2021-10-13 18:18
@pururaj987 It would be best to put a link to the source code (GitHub) in the footer.
Can you suggest a suitable location for the same?

**Comment by TheGreatFellow** [comment] 2021-10-25 14:39
@ayushk1804 can you assign this issue to me?

**Comment by SparshKesari** [comment] 2021-10-26 15:13
@TheGreatFellow, The issue is assigned to you. Please start working on it.

**Closed as completed** 2021-10-31 04:25 UTC
Labels: good first issue
